import * as THREE from 'three';
import { createTrickSimulation } from './trickSimulation.ts';
import type { GameRuntime } from './types.ts';

export function createGameRuntime(): GameRuntime {
    return {
        keys: {
            w: false,
            a: false,
            s: false,
            d: false,
            q: false,
            e: false,
            f: false,
            space: false,
            shift: false,
        },
        jumpInput: { queuedAt: 0 },
        physics: {
            mass: 70,
            thrustForce: 2.75,
            hoverStiffness: 1.65,
            hoverDamping: 0.32,
            maxHoverForce: 4.8,
            maxHoverRange: 1.05,
            coastFriction: 0.002,
            coastDrag: 0.00075,
            airDrag: 0.015,
            maxSpeed: 1.15,
            rotationSpeed: 0.04,
            gravity: 0.0035,
            jumpImpulse: 0.14,
            tiltSmoothing: 0.18,
            driftSlideMultiplier: 0.08,
            slideGrip: 0.014,
            driftGripMultiplier: 0.32,
            driftThreshold: 0.14,
            boostMultiplier: 1.85,
            boostAccelMultiplier: 2.2,
            cameraBaseFov: 60,
            cameraMaxFov: 84,
            heading: 0,
            velocity: new THREE.Vector3(),
            isGrounded: true,
            airTime: 0,
        },
        cameraControl: {
            yaw: Math.PI,
            pitch: 0.38,
            distance: 14,
            minDistance: 5,
            maxDistance: 42,
            sensitivity: 0.006,
            zoomSensitivity: 0.0015,
            autoFollowStrength: 0.025,
            fovSmoothing: 0.08,
            isDragging: false,
            lastX: 0,
            lastY: 0,
        },
        scratch: {
            upAxis: new THREE.Vector3(0, 1, 0),
            camOffset: new THREE.Vector3(),
            targetCamPos: new THREE.Vector3(),
            lookTarget: new THREE.Vector3(),
            rightVector: new THREE.Vector3(),
            terrainNormal: new THREE.Vector3(0, 1, 0),
            normalProbeA: new THREE.Vector3(),
            normalProbeB: new THREE.Vector3(),
            normalProbeC: new THREE.Vector3(),
            playerMatrix: new THREE.Matrix4(),
            targetPlayerQuat: new THREE.Quaternion(),
            baseForward: new THREE.Vector3(),
            slopeForward: new THREE.Vector3(),
            slopeRight: new THREE.Vector3(),
            acceleration: new THREE.Vector3(),
            normalAcceleration: new THREE.Vector3(),
            tangentVelocity: new THREE.Vector3(),
        },
        parts: null,
        trickState: createTrickSimulation(),
        frameHud: {},
        multiplayerClient: null,
    };
}

export function getPlayerRoot(runtime: GameRuntime) {
    return runtime.parts?.playerGroup ?? runtime.parts?.group ?? null;
}
